yl_factory:
    resource: "@YLFactoryBundle/Resources/config/routing.yml"
    prefix:   /factory

##CORE APP BUNDLE ROUTING

yl_core_app:
    resource: "@YLCoreAppBundle/Resources/config/routing.yml"

##FOS USER BUNDLE ROUTING

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"


##COMPANY BUNDLE ROUTING
yl_company:
    resource: "@YLCompanyBundle/Resources/config/routing.yml"
    prefix:   /api
