<?php

namespace YL\UserBundle\Repository;

/**
 * PreteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreteurRepository extends \Doctrine\ORM\EntityRepository
{
}
